name = "vetappfrontend"
main = "./src/worker/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[observability]
enabled = true

[triggers]
crons = [
  "1 * * * *"
  # "*/5 * * * *"
]

[assets]
directory = "./dist/client"
not_found_handling = "single-page-application"

[vars]
PROJECT_NAME ="vetappfrontend"
VITE_APP_NETWORK = "testnet"

amm="0xf4ca29658de9f34480a6b35a3a64e91320e45747e023525aa8c7d31d4fdf1566"
bonding_curve="0xb0cfb7e99d198710b9531166793389d1eef0b83cc9b60d5d37192e47f8a72352"
clmm="0x08c25945c927dbd80cfbbd5e3692c67c77f2ac783cb6b7bf68d723a5cbf1ba62"
escrow="0xd65e4d64e11f684c3e6033b729e8123583955a49fd562fb11abf54e552b39159"
gauge="0xf9ab976e24945f228b675211abc26dad37240f58995eebc9ed886d2b5585d89e"
nft_springboard="0x7a0f3fa065bf6fe96ccfcefe1d55a818cb83f8ee426c345e73b4d037e0ccf220"
stable="0xf3b5dc05f0ba56ced30c72f587da2a0810043612eee2e45394c11f49cf1cd341"
tapp="0x6e417737bdde4471840e76fdbfea33e84d6dd5787663299c5126deefead86904"
ve_tapp="0x7d7698e29cd55b892e1b18240f43f99276c8f45a5b063b1c311cece04c243e12"
ve_tapp_lib="0xdb1c6ffcbd45609701d72064aacfde45cf54d0dba61408ef73d5825baec99896"
